const data = {
  products: [
    {
      _id: '1',
      name: 'Hawaii Slim Shirt',
      category: 'Shirts',
      image: 'https://m.media-amazon.com/images/I/91Bab4-HcNL._AC_UL320_.jpg',
      price: '120',
      brand: 'Fonsus Products',
      ratings: 4.5,
      numReviews: 10,
      description: 'Summer Beach Slim Fit Hawaiian Outfit',
    },
    {
      _id: '2',
      name: 'Slim-Fit Shirt',
      category: 'Shirts',
      image: 'https://m.media-amazon.com/images/I/819wcaoF7FL._AC_UL320_.jpg',
      price: 140.99,
      brand: 'Fonsus Products',
      ratings: 3.5,
      numReviews: 10,
      description: 'Summer Slim Fit Outfit',
    },
    {
      _id: '3',
      name: 'Mens Fittness Shirt',
      category: 'Shirts',
      image: 'https://m.media-amazon.com/images/I/719XKm4kyHL._AC_UL320_.jpg',
      price: 107.99,
      brand: 'Fonsus Products',
      ratings: 4.0,
      numReviews: 7,
      description: 'Fittness Slim Fit Shirts',
    },
    {
      _id: '4',
      name: 'Buck Camping Shirt',
      category: 'Shirts',
      image: 'https://m.media-amazon.com/images/I/91WqPt6KaUS._AC_UL320_.jpg',
      price: 208.99,
      brand: 'Fonsus Products',
      ratings: 3.0,
      numReviews: 8,
      description: 'Camping been suited for the forest',
    },
    {
      _id: '5',
      name: 'Golf Polo Short Sleeve Shirt',
      category: 'Shirts',
      image: 'https://m.media-amazon.com/images/I/51OYS0EJwSL._AC_UL320_.jpg',
      price: 390.99,
      brand: 'Fonsus Products',
      ratings: 5.0,
      numReviews: 10,
      description:
        'Golfing Polo shirts by Nike, Comfortable and Relaxing when you take that swing',
    },
    {
      _id: '6',
      name: 'Wrangler Jean from Rick and Morty',
      category: 'Jeans',
      image: 'https://m.media-amazon.com/images/I/81HIcavdH6L._AC_UL320_.jpg',
      price: 900.99,
      brand: 'Fonsus Products',
      ratings: 4.5,
      numReviews: 9,
      description: 'Wrangler Jean from Rick and Morty Episode 9, Season 4',
    },
    {
      _id: '7',
      name: 'Longbida Ripped Slim Jeans',
      category: 'Jeans',
      image: 'https://m.media-amazon.com/images/I/51tGPNHk4pL._AC_UL320_.jpg',
      price: 100.89,
      brand: 'Fonsus Products',
      ratings: 2.5,
      numReviews: 4,
      description: 'Ripped Jeans for Young People, Express Yourself',
    },
    {
      _id: '8',
      name: 'Lee Mens Series Extreme Athletic Jeans',
      category: 'Jeans',
      image: 'https://m.media-amazon.com/images/I/91LTm66RFQL._AC_UL320_.jpg',
      price: 189.99,
      brand: 'Fonsus Products',
      ratings: 4.0,
      numReviews: 7,
      description: 'Series Extreme Athletic Jeans, John Wick wore this',
    },
  ],
}

export default data
